// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgyyisjxrzstiegcfobf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZneXlpc2p4cnpzdGllZ2Nmb2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2ODUyOTcsImV4cCI6MjA2OTI2MTI5N30.lvwvc1VuKSsdo5hD96jNBORTyRJ3C8oRWHYClrvD1Io";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});